### ISSUE TITLE
FIXME

### ISSUE THREAD

**Issue by tenhishadow** [tide34/nextcloud#7]
## Circleci config:

**Useless**:
https://github.com/tide34/nextcloud/blob/a3e2bc1e80465905a4ca4b6302920b7deb155614/.circleci/config.yml#L11
https://github.com/tide34/nextcloud/blob/a3e2bc1e80465905a4ca4b6302920b7deb155614/.circleci/config.yml#L37
https://github.com/tide34/nextcloud/blob/a3e2bc1e80465905a4ca4b6302920b7deb155614/.circleci/config.yml#L57
https://github.com/tide34/nextcloud/blob/a3e2bc1e80465905a4ca4b6302920b7deb155614/.circleci/config.yml#L45 ( twice )

**Wrong**:

100500 раз обсудили:
```curl --cacert ./web/certs/domain.crt -I  https://cloud.example.com:8080/login | grep '200 OK'```

manual from nextcloud:
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html
это более правильный тест и логина и функциональности выдавать приложениям пароли от админа.

```
curl 'https://127.0.0.1:8080/ocs/v2.php/core/getapppassword' \
  -H "Host: cloud.example.com" \
  -H 'OCS-APIRequest: true' \
  --insecure \
  --user gleb:Aa1234
```

then check 200 with smth like this:
```| grep -q '200'```

**Comment by tide34** [comment]
All issues fixed.
